import {
  ConnectWallet,
  useAddress,
  useClaimNFT,
  useContract,
} from "@thirdweb-dev/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { contract } = useContract(
    process.env.NEXT_PUBLIC_NFT_DROP_ADDRESS,
    "nft-drop"
  );
  const { mutateAsync: claim, isLoading } = useClaimNFT(contract);
  const address = useAddress();

  const claimNFT = async () => {
    try {
      const data = await claim({ quantity: 1 });
      alert(`Claim successful, token ID ${data[0].id.toString()}`);
    } catch (err) {
      console.error(err);
      alert(err);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: "200px" }}>
        <ConnectWallet />
      </div>

      {address && (
        <div>
          <button onClick={claimNFT} disabled={isLoading}>
            Claim NFT!
          </button>
        </div>
      )}
    </div>
  );
}
